[package]
name = "g4ssg-core"
version = "0.1.0"
edition = "2024"
authors = ["Markku Sukanen <markku.sukanen@gmail.com>"]
license-file = "LICENSE"
maintenance = { status = "experimental" }

[dependencies]
rand = "0.9.1"
dicebag = "0.3"
msuk-scifi = "0.2.1"
once_cell = "1.21.3"
log = "0.4"
env_logger = "0.11.8"
rayon = "1.10"
